sysAcad/grades/urls.py
from django.urls import path

from .views import GradeDetailAPIView, GradeList

urlpatterns = [
    path("", GradeList.as_view()),
    path("<int:id>", GradeDetailAPIView.as_view()),
]

sysAcad/professor/urls.py
from django.urls import path
from professor import views
from authentication.views import user_login
urlpatterns = [
    path('home/', views.home, name='professor_home'),
    path('remove_professor/', views.remove_professor, name='remove_professor'),
    path('home/edit_info/', views.edit_professor, name='edit_professor'),
    path('register-in-class/', views.register_in_class, name='register_in_class'),
    path('my-classes/', views.view_current_classes, name='view_current_classes'),
    path('turmas/<int:class_id>/estudantes/', views.view_students_in_class, name='view_students_in_class'),
    path('complete_class/<int:class_id>/', views.complete_class, name='complete_class'),
]

sysAcad/sysAcad/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("authentication.urls")),
    path('student/', include('student.urls')),
    path('professor/', include('professor.urls')),
]

sysAcad/sysacad/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from classes.urls import *
from courses.urls import *
from grades.urls import *
from professors.urls import *
from students.urls import *
from subjects.urls import *

schema_view = get_schema_view(
    openapi.Info(
        title="SysAcad",
        default_version="v1",
        description="API for managing movies, theaters, and sessions in a cinema",
        contact=openapi.Contact(email="jonas.nogueira@aluno.uece.br"),
    ),
    public=True,
)

urlpatterns = [
    path(
        "",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("api/classes/", include("classes.urls")),
    path("api/courses/", include("courses.urls")),
    path("api/grades/", include("grades.urls")),
    path("api/professors/", include("professors.urls")),
    path("api/students/", include("students.urls")),
    path("api/subjects/", include("subjects.urls")),
    path("admin/", admin.site.urls),
]

sysAcad/professor/models.py
from django.db import models
from django.conf import settings
from datetime import date

class Professor(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    email = models.EmailField()
    name = models.CharField(max_length=64)
    cellphone = models.CharField(max_length=14)
    birth_date = models.DateField(auto_now=False, auto_now_add=False)

    def get_age(self):
        today = date.today()
        age = today.year - self.birth_date.year - ((today.month, today.day) < (self.birth_date.month, self.birth_date.day))
        return age

    def __str__(self):
        return self.name
    
    def get_first_name(self):
        names = self.name.split()
        return names[0]

sysAcad/professors/models.py
from django.db import models


class Professor(models.Model):

    email = models.EmailField()
    name = models.CharField(max_length=64)
    cellphone = models.CharField(max_length=14)
    birth_date = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.name

sysAcad/professor/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from users.forms import EditInfoForm
from classes.models import Classes
from grade.models import Grade
from .models import Professor


def get_logged_in_professor(request):
    try:
        return Professor.objects.get(user=request.user)
    except Professor.DoesNotExist:
        return None

@login_required
def home(request):
    professor = get_logged_in_professor(request)
    if not professor:
        return redirect('login')  # Redireciona se o professor não for encontrado
    return render(request, "professor/home.html", {"professor": professor})

def remove_professor(request):
    if request.method == "GET":
        try:
            professor = Professor.objects.get(user=request.user)
            user = professor.user
            user.delete()
            messages.success(request, "Conta excluída com sucesso")
            return redirect("login")
        except Professor.DoesNotExist:
            messages.error(request, "Erro ao excluir a conta")
            return redirect(reverse("professor_home"))


def edit_professor(request):
    try:
        professor = Professor.objects.get(user=request.user)

    except Professor.DoesNotExist:
        messages.error(request, "Professor não encontrado")
        return redirect(reverse("professor_home"))

    if request.method == "POST":
        form = EditInfoForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            cellphone = form.cleaned_data.get("cellphone")
            password = form.cleaned_data.get("password")
            birth_date = form.cleaned_data.get("birth_date")

            professor.name = name
            professor.email = email
            professor.cellphone = cellphone
            professor.password = password
            professor.birth_date = birth_date

            user = professor.user
            user.username = email
            if password:
                user.set_password(password)
            user.save()
            professor.save()
            login(request, user)

            messages.success(request, "Informações atualizadas com sucesso.")
            return redirect(reverse("edit_professor"))

        else:
            messages.error(request, "Erro ao atualizar informações")

    else:
        form = EditInfoForm(
            initial={
                "name": professor.name,
                "email": professor.email,
                "cellphone": professor.cellphone,
                "birth_date": professor.birth_date,
            }
        )
    return render(request, "professor/edit_info.html", {
        "form": form,
        "professor": professor
        })

@login_required
def register_in_class(request):
    professor = Professor.objects.get(user=request.user)
    classes = Classes.objects.filter(professor__isnull=True)

    print(classes)
    if request.method == "POST":
        if request.user.is_authenticated:
            try:
                selected_classes = request.POST.getlist("classes")

                if not selected_classes:
                    messages.error(request, "Nenhuma turma selecionada")
                    return redirect("register_in_class")

                for class_id in selected_classes:
                    class_instance = Classes.objects.get(id=class_id)

                    professor.classes.add(class_instance)

                messages.success(request, "Turmas matriculadas com sucesso!")
                return redirect("register_in_class")

            except Professor.DoesNotExist:
                messages.error(request, "Estudante não encontrado")
                return redirect("login")

            except Classes.DoesNotExist:
                messages.error(request, "Uma ou mais turmas não existem")
                return redirect("register_in_class")

    return render(request, "professor/register_in_class.html", {"classes": classes, "professor": professor})


@login_required
def view_current_classes(request):
    professor = get_logged_in_professor(request)  # Usa a função para obter o professor logado
    if not professor:
        return redirect('login')  # Redireciona se o professor não for encontrado

    # Obter todas as turmas atribuídas ao professor logado
    current_classes = Classes.objects.filter(professor=professor)

    return render(request, 'professor/current_classes.html', {
        'professor': professor,  
        'current_classes': current_classes
    })

@login_required
def view_students_in_class(request, class_id):
    professor = get_logged_in_professor(request)
    class_instance = get_object_or_404(Classes, id=class_id)

    if class_instance.professor.user != request.user:
        messages.error(request, "Você não tem permissão para ver os estudantes dessa turma.")
        return redirect('view_current_classes')

    students = class_instance.students.all()
    grades_by_student = {
        grade.student.user.id: grade  
        for grade in Grade.objects.filter(student__in=students, subject=class_instance.subject)
    }

    if request.method == 'POST':
        for student in students:
            grade1 = request.POST.get(f'grade1_{student.user.id}')
            grade2 = request.POST.get(f'grade2_{student.user.id}')
            grade3 = request.POST.get(f'grade3_{student.user.id}')

            # Obter ou criar o objeto de Grade correspondente
            grade, created = Grade.objects.get_or_create(student=student, subject=class_instance.subject)

            # Atualizar as notas se elas forem válidas
            if grade1 is not None:
                try:
                    grade.grade1 = float(grade1) if grade1 else None
                except ValueError:
                    messages.error(request, f"Nota 1 inválida para o aluno {student.name}")
                    return redirect('view_students_in_class', class_id=class_id)

            if grade2 is not None:
                try:
                    grade.grade2 = float(grade2) if grade2 else None
                except ValueError:
                    messages.error(request, f"Nota 2 inválida para o aluno {student.name}")
                    return redirect('view_students_in_class', class_id=class_id)

            if grade3 is not None:
                try:
                    grade.grade3 = float(grade3) if grade3 else None
                except ValueError:
                    messages.error(request, f"Nota 3 inválida para o aluno {student.name}")
                    continue

            grade.save()  # Salva o objeto Grade após atualizar as notas

        messages.success(request, "Notas atualizadas com sucesso.")
        return redirect('view_students_in_class', class_id=class_id)

    return render(request, 'professor/students_in_class.html', {
        'class_instance': class_instance,
        'students': students,
        'grades_by_student': grades_by_student,
        'professor': professor
    })

@login_required
def complete_class(request, class_id):
    class_instance = get_object_or_404(Classes, id=class_id)

    if class_instance.professor.user != request.user:
        messages.error(request, "Você não tem permissão para concluir esta turma.")
        return redirect('view_current_classes')

    if request.method == 'POST':
        if class_instance.all_grades_assigned():
            class_instance.is_completed = True
            class_instance.save()
            messages.success(request, "Turma concluída com sucesso.")
            return redirect('view_current_classes')
        else:
            messages.error(request, "Não é possível concluir a turma. Certifique-se de que todas as notas foram atribuídas.")

    return render(request, 'professor/complete_class.html', {
        'class_instance': class_instance
    })

@login_required
def view_completed_classes(request):
    completed_classes = Classes.objects.filter(professor__user=request.user, is_completed=True)  # Filtra turmas concluídas
    return render(request, 'professor/completed_classes.html', {'completed_classes': completed_classes})

sysAcad/professors/views.py
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView

from .filters import ProfessorFilter
from .models import Professor
from .serializers import ProfessorSerializer


class ProfessorList(ListCreateAPIView):
    serializer_class = ProfessorSerializer
    queryset = Professor.objects.all()

    def perform_create(self, serializer):
        serializer.save()

    def get_queryset(self):
        return self.queryset.all()


class ProfessorDetailAPIView(RetrieveUpdateDestroyAPIView):
    serializer_class = ProfessorSerializer
    queryset = Professor.objects.all()
    lookup_field = "id"

    def get_queryset(self):
        return self.queryset.all()

sysAcad/professor/templates/professor/current_classes.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de Gestão Acadêmica para alunos.">
        <meta name="keywords" content="gestão acadêmica, matrícula, histórico escolar">
        <meta name="author" content="SysCad">
        <title>Menu Principal - SysCad</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'professor/css/professor_classes.css' %}">
    </head>
    <body>
        <header class="header">
            <img src="{% static 'professor/images/uece-logo.png' %}" alt="Example Image">

            <p>Bem-vindo, {{ professor.get_first_name }} </p>
        </header>

        <nav class="navigation-bar">
            <ul>
                <li><a href="{% url 'register_in_class' %}" class="btn">Cadastrar-se em Turma</a></li>
                <li><a href="{% url 'edit_professor' %}">Dados Pessoais</a></li>
                <li><a href="{% url 'professor_home'%}" class="btn">Voltar</a></li>
            </ul>
        </nav>

        <main>
            <section class="enrolled-subjects">

                <h3 class="title">Minhas Turmas</h3>

                <table id="student-info-table">
                    <tbody>
                        <tr>
                            <td class="bold">Professor:</td>
                            <td class="uppercase">{{ professor.get_first_name }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="container-table">
                    <table class="table table-bordered table-strip">
                        <thead>
                            <tr>
                                <th>Disciplina</th>
                                <th>Horário</th>
                                <th>Sala</th>
                                <th>Vagas</th>
                                <th>Alunos Matriculados</th>
                                <th>Estudantes</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for class in current_classes %}
                                <tr>
                                    <td>{{ class.subject.name }}</td>
                                    <td>{{ class.start_time }} - {{ class.end_time }}</td>
                                    <td>{{ class.classroom }}</td>
                                    <td>{{ class.vacancies }}</td>
                                    <td>{{ class.students.count }}</td>
                                    <td>
                                        <a href="{% url 'view_students_in_class' class.id %}" class="btn btn-primary">Ver Estudantes</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
            </section>
        </main>
    </body>
</html>

sysAcad/professor/templates/professor/edit_info.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Atualize suas informações pessoais no Sistema de Gestão Acadêmica.">
        <meta name="keywords" content="gestão acadêmica, atualizar dados, excluir conta, formulário">
        <meta name="author" content="SysAcad">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Atualizar Dados - SysAcad</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'professor/css/edit_info.css' %}">
    </head>
    <body>
        <header class="header">
            <img src="{% static 'professor/images/uece-logo.png' %}" alt="Logo UECE">

            <p>Bem-vindo, {{ professor.get_first_name }} </p>
        </header>

        <nav class="navigation-bar">
            <ul>
                <li><a href="{% url 'view_current_classes'%}" class="btn">Suas Turmas</a></li>
                <li><a href="{% url 'register_in_class' %}" class="btn">Cadastrar-se em Turma</a></li>
                <li><a href="{% url 'professor_home' %}" class="btn">Voltar</a></li>
            </ul>
        </nav>

        <div class="container">
            <div class="form-header">
                <h1>Atualizar Dados</h1>
            </div>

            <form method="POST" class="form-update-account">
                {% if messages %}
                <div>
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        <p>{{ message }}</p>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Nome completo</label>
                    {{ form.name }}
                    {% if form.name.errors %}
                        <div class="error">{{ form.name.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                        <div class="error">{{ form.email.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.cellphone.id_for_label }}">Celular</label>
                    {{ form.cellphone }}
                    {% if form.cellphone.errors %}
                        <div class="error">{{ form.cellphone.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.password.id_for_label }}">Senha</label>
                    {{ form.password }}
                    {% if form.password.errors %}
                        <div class="error">{{ form.password.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.password_confirm.id_for_label }}">Confirmar Senha</label>
                    {{ form.password_confirm }}
                    {% if form.password_confirm.errors %}
                        <div class="error">{{ form.password_confirm.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-group">
                    <label for="{{ form.birth_date.id_for_label }}">Data de nascimento</label>
                    {{ form.birth_date }}
                    {% if form.birth_date.errors %}
                        <div class="error">{{ form.birth_date.errors }}</div>
                    {% endif %}
                </div>
                <div class="form-buttons">
                    <button type="submit" class="btn-update">Atualizar dados</button>
                    <a href="{% url 'remove_professor' %}" class="btn-remove-account" onclick="return confirm('Tem certeza que deseja excluir essa conta?');">Excluir conta</a>
                </div>
            </form>
        </div>
    </body>
</html>

sysAcad/professor/templates/professor/home.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de Gestão Acadêmica para alunos.">
        <meta name="keywords" content="gestão acadêmica, matrícula, histórico escolar">
        <meta name="author" content="SysCad">
        <title>Menu Principal - SysCad</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'professor/css/home.css' %}">
    </head>
    <body>
        
        <header class="header">
            <img src="{% static 'professor/images/uece-logo.png' %}" alt="Example Image">

            <p>Bem-vindo, {{ professor.get_first_name }} </p>
        </header>

        <nav class="navigation-bar">
            <ul>
                <li><a href="{% url 'view_current_classes'%}" class="btn">Suas Turmas</a></li>
                <li><a href="{% url 'register_in_class' %}" class="btn">Cadastrar-se em Turma</a></li>
                <li><a href="{% url 'edit_professor' %}">Dados Pessoais</a></li>
                <li><a href="{% url 'login' %}" class="btn">Sair</a></li>
            </ul>
        </nav>

        <main>
            <section class="enrolled-subjects">

                <h3 class="title">Dados Institucionais</h3>

                <table id="student-info-table">
                    <tbody>
                        <tr>
                            <td class="bold">Professor:</td>
                            <td class="uppercase">{{ professor.get_first_name }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="container-table">
                    <table class="table table-bordered table-strip">
                        <thead>
                            <tr>
                                <th>Matricula</th>
                                <th>Nome</th>
                                <th>Email</th>
                                <th>Idade</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ professor.user_id }}</td>
                                <td>{{ professor.name }}</td>
                                <td>{{ professor.email }}</td>
                                <td>{{ professor.get_age }}</td>
                            </tr>
                        </tbody>
                    </table>
            </section>
        </main>
    </body>
</html>

sysAcad/professor/templates/professor/register_in_class.html
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de Gestão Acadêmica para alunos.">
        <meta name="keywords" content="gestão acadêmica, matrícula, histórico escolar">
        <meta name="author" content="SysCad">
        <title>Menu Principal - SysCad</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'professor/css/professor_register_classes.css' %}">
    </head>
    <body>
        <!-- Header section -->
        <header class="header">
            <img src="{% static 'professor/images/uece-logo.png' %}" alt="Example Image">
            <p>Bem-vindo, {{ professor.get_first_name }} </p>
        </header>

        <nav class="navigation-bar">
            <ul>
                <li><a href="{% url 'view_current_classes'%}" class="btn">Suas Turmas</a></li>
                <li><a href="{% url 'edit_professor' %}">Dados Pessoais</a></li>
                <li><a href="{% url 'professor_home'%}" class="btn">Voltar</a></li>
            </ul>
        </nav>

        <main>
            <section class="enrolled-subjects">
                <h3 class="title">Cadastro em Turmas</h3>

                <table id="student-info-table">
                    <tbody>
                        <tr>
                            <td class="bold">Professor:</td>
                            <td class="uppercase">{{ professor.get_first_name }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="container-table">
                    {% if classes %}
                        <form method="post">
                            {% csrf_token %}
                            {% if messages %}
                            <div>
                                {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}">
                                    <p>{{ message }}</p>
                                </div>
                                {% endfor %}
                            </div>
                            {% endif %}
                            <table class="table table-bordered table-strip">
                                <thead>
                                    <tr>
                                        <th>Disciplina</th>
                                        <th>Horário</th>
                                        <th>Sala</th>
                                        <th>Vagas</th>
                                        <th>Selecionar</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for class in classes %}
                                        <tr>
                                            <td>
                                                <input type="checkbox" id="class_{{ class.id }}" name="classes" value="{{ class.id }}">
                                            </td>
                                            <td>{{ class.subject.name }}</td>
                                            <td>
                                                {% for day in class.days_of_week.all %}
                                                {{ day.get_name_display }}{% if not forloop.last %}, {% endif %}
                                                {% endfor %}
                                            </td>
                                            <td>{{ class.classroom }}</td>
                                            <td>{{ class.vacancies }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary">Cadastrar-se na turma</button>
                        </form>
                    {% else %}
                        <p>Não há turmas disponíveis para cadastro.</p>
                    {% endif %}
                </div>
            </section>
        </main>
    </body>
</html>

sysAcad/professor/templates/professor/students_in_class.html
{% load custom_filters %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Sistema de Gestão Acadêmica para alunos.">
        <meta name="keywords" content="gestão acadêmica, matrícula, histórico escolar">
        <meta name="author" content="SysCad">
        <title>Menu Principal - SysCad</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'professor/css/professor_register_classes.css' %}">
    </head>

    <body>
        <header class="header">
            <img src="{% static 'professor/images/uece-logo.png' %}" alt="Example Image">
            <p>Bem-vindo, {{ professor.get_first_name }} </p>
        </header>

        <nav class="navigation-bar">
            <ul>
                <li><a href="{% url 'view_current_classes' %}" class="btn btn-primary">Voltar</a></li>
            </ul>
        </nav>

        <main>
            <section class="enrolled-subjects">
                <h3 class="title">Estudantes na Turma: {{ class_instance.subject.name }}</h3>

                <table id="student-info-table">
                    <tbody>
                        <tr>
                            <td class="bold">Professor:</td>
                            <td class="uppercase">{{ professor.get_first_name }}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="container-table">
                    {% if students %}
                    <form method="post">
                        {% csrf_token %}
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Nota 1</th>
                                    <th>Nota 2</th>
                                    <th>Nota 3</th>
                                    <th>Média</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for student in students %}
                                    {% with grades_for_student=grades_by_student|get_item:student.user_id %}
                                        <tr>
                                            <td>{{ student.name }}</td>
                                            <td>
                                                <input type="number" step="0.1" name="grade1_{{ student.user.id }}" 
                                                       value="{% if grades_for_student %}{{ grades_for_student.grade1|default:'0' }}{% else %}0{% endif %}" min="0" max="10">
                                            </td>
                                            <td>
                                                <input type="number" step="0.1" name="grade2_{{ student.user.id }}" 
                                                       value="{% if grades_for_student %}{{ grades_for_student.grade2|default:'0' }}{% else %}0{% endif %}" min="0" max="10">
                                            </td>
                                            <td>
                                                <input type="number" step="0.1" name="grade3_{{ student.user.id }}" 
                                                       value="{% if grades_for_student %}{{ grades_for_student.grade3|default:'0' }}{% else %}0{% endif %}" min="0" max="10">
                                            </td>
                                            <td>
                                                {% if grades_for_student %}
                                                    {{ grades_for_student.calculate_average|default:0|floatformat:2 }}
                                                {% else %}
                                                    --
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endwith %}
                                {% endfor %}
                            </tbody>
                        </table>
                        <button type="submit" class="btn btn-primary">Salvar Notas</button>
                    </form>
                    {% else %}
                        <p>Não há estudantes cadastrados nesta turma.</p>   
                    {% endif %}   
                </div>
            </section>
        </main>
    </body>
</html>